### ISSUE TITLE
Question: secret on Mifare Classic

### ISSUE THREAD

**Issue by Rotzbua** [blinzelaffe/roseguarden#9]
Hi, is the secret on the token only set once or is it changed every time it is used?

**Comment by mdrobisch** [comment]
Hi, there are to secrets, one personal secret to identify the user and one global to encrypt the tags.
At the moment both of them are static after creation. This due to the fact that the communication to the tag is not quite stable every time and a write process could fail from time to time. I should have a look at this and provide a changing token. Maybe someone else is interested and implement this feature.

**Comment by Rotzbua** [comment]
Thanks for your answer.
I just ask, because Mifare Classic can be easily cloned and security is broken since 2008. So I was interested how you detect evil ppl. 
If you plan to implement some protection, maybe have a look at MIFARE Increment command. This command should be faster than writing data. (I didnt tested yet)
Best
